version: "3.3"

services:

  server:
    container_name: jagrik-server
    image: jagrik:server
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /usr/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind