version: "3.3"

services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    networks:
      - jagrik

  server:
    container_name: jagrik-server
    image: jagrik:server
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /usr/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb

  client:
    container_name: client
    image: client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /usr/app/node_modules
    depends_on:
      - server
    networks:
      - jagrik

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - server
      - client
    networks:
      - jagrik

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

networks:
  jagrik: 
    driver: bridge